version: "3.8"

services:
  jenkins:
    image: jenkins/jenkins:lts-jdk11
    container_name: jenkins-instance
    volumes:
      - jenkins-data:/var/jenkins_home:rw
    ports:
      - 8080:8080

volumes:
  jenkins-data:
    name: jenkins-data